default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: admin
  host: localhost

development:
  <<: *default
  database: project_management_system_development

test:
  <<: *default
  database: project_management_system_test

production:
  <<: *default
  database: project_management_system_production
  username: postgres
  password: admin
